packages:
  - "packages/*"

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@stellar/stellar-sdk"
  - "bigint-buffer"
  - "blake-hash"
  - "bufferutil"
  - "msgpackr-extract"
  - "prisma"
  - "protobufjs"
  - "tiny-secp256k1"
  - "usb"
  - "utf-8-validate"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@stellar/stellar-sdk': true
  bigint-buffer: true
  blake-hash: true
  bufferutil: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  tiny-secp256k1: true
  usb: true
  utf-8-validate: true
